### ISSUE TITLE
Ogg #2 --> tuneable/pulse tick boxes required to be ticked when creating new laser

### ISSUE THREAD

**Issue by stephenogg** [WU-BIMAC/MicroMetaApp-React#363] opened 2021-04-05 16:22 UTC
**Describe the bug**
When Adding a new laser light source to a system, if I don't check both the tuneable and pulse tick boxes, I get an error saying that these elements are required when I try to confirm the laser. After confirmation, I can go back and deselect these elements, but I don't think I should have to select them when creating the laser, if its not pulsed or tuneable.

**Desktop (please complete the following information):**
 - OS: MacOS
 - micro-meta-app-electron
 - Version 0.46.5-b1-0 (0.46.5-b1-0)

**Comment by strambc** [comment] 2021-04-05 16:39
Hi @stephenogg 
thank you for the comment.
This is a known issue #105 
and it will be dealt with in the next release.
It is related to how a boolean field is death with when it is REQUIRED.
Essentially, the problem is that the software has to register and interaction (click and un-click) to record as validated.
We know this is annoying and we will definitely deal with it. 
I will close this issue as it is the same as #105

**Closed by strambc** 2021-04-05 16:39 UTC
Labels: High, Next Iteration, bug
